name: Golang-Release

on:

  push:
    branches: ["master", "main"]
    tags:
      - v*

jobs:

  # Technically both workflow_run and push will trigger
  # the pipeline, then it will falsely try to create a release
  # and fail. To avoid this, start with a ref on tags and
  # successful completion of CI
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    uses: mattdood/common-ci/.github/workflows/golang-release.yml@v0.0.6
    secrets:
      GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
    if: ${{ startsWith(github.ref, 'refs/tags/v')}}
