name: Golang-Release

on:

  push:
    branches: ["master", "main"]
    tags:
      - v*

jobs:

  # Technically both workflow_run and push will trigger
  # the pipeline, then it will falsely try to create a release
  # and fail. To avoid this, start with a ref on tags and
  # successful completion of CI
  release:
    uses: mattdood/common-ci/.github/workflows/golang-release.yml@v0.0.6
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
