name: Golang-Release

on:

  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: ["master", "main"]

  push:
    branches: ["master", "main"]
    tags:
      - v*

jobs:

  release:
    uses: mattdood/common-ci/.github/workflows/golang-release.yml@v0.0.5
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
