name: Golang-Release

on:

  workflow_run:
    workflows: [CI]
    types: [completed]
  tags:
      - '*'

jobs:

  release:
    uses: mattdood/workflows.github/workflows/golang-release.yml@v0.0.3
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
